version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    # volumes:
    #   - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # depends_on:
    #   - mongo # Example dependency on a database service

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
  mongo:
    image: mongo:latest
    container_name: "cw_llm_mongo"
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: "cw_llm"
      MONGO_INITDB_ROOT_PASSWORD: "cw_llm"
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - local
    restart: always

volumes:
  mongo_data:
  qdrant_data:
  
networks:
  local:
    driver: bridge

