settings:
  docker:
    parent_image: 992382797823.dkr.ecr.eu-central-1.amazonaws.com/zenml-rlwlcs:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false
    
parameters:
  user_full_name: David Knapp # [First Name(s)] [Last Name]
  links:
    # cwordinfo
    - https://www.xwordinfo.com/Crossword?date=1/1/2025
